# Generated by Django 6.0.5 on 2026-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SEO Slug методики')),
                ('title', models.CharField(max_length=255, verbose_name='Название методики')),
                ('image', models.ImageField(upload_to='methods/', verbose_name='Изображение для карточки методики')),
                ('short_desc', models.TextField(verbose_name='Краткое описание')),
                ('full_desc', models.TextField(blank=True, null=True, verbose_name='Полное описание для страницы методики')),
            ],
            options={
                'verbose_name': 'Методики',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SEO Slug врача')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Врача')),
                ('exp', models.CharField(max_length=50, verbose_name='Стаж работы')),
                ('desc', models.TextField(verbose_name='Короткое интро для карточки')),
                ('full_bio', models.TextField(verbose_name='Развернутая биография')),
                ('image', models.ImageField(upload_to='doctors/', verbose_name='Фотография')),
                ('video_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID видео YouTube')),
                ('methods', models.ManyToManyField(blank=True, related_name='doctors', to='clinic.medicalmethod', verbose_name='Практикуемые методики')),
            ],
            options={
                'verbose_name': 'Врачи',
                'ordering': ['id'],
            },
        ),
    ]
