# Generated by Django 6.0.5 on 2026-05-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='medicalmethod',
            options={'verbose_name': 'Методика', 'verbose_name_plural': 'Методики'},
        ),
    ]
