# Generated by Django 6.0.5 on 2026-05-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_doctor_options_alter_medicalmethod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='Врач-специалист', max_length=255, verbose_name='Должность/Роль'),
        ),
        migrations.CreateModel(
            name='MethodGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='methods/gallery/', verbose_name='Дополнительное фото')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinic.medicalmethod', verbose_name='Методика')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Галерея картинок методики',
            },
        ),
    ]
