# Generated by Django 6.0.5 on 2026-05-31 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_role_methodgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.CreateModel(
            name='DoctorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/gallery/', verbose_name='Дополнительное фото')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['id'],
            },
        ),
    ]
