# Generated by Django 6.0.5 on 2026-05-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_doctor_options_remove_doctor_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='doctorgallery',
            options={'verbose_name': 'Фотография галереи врача', 'verbose_name_plural': 'Галерея картинок врача'},
        ),
        migrations.AlterField(
            model_name='doctorgallery',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinic.doctor', verbose_name='Врач'),
        ),
    ]
