# Generated by Django 6.0.5 on 2026-05-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_doctor_options_alter_doctorgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название награды/диплома')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Скан/Фотография награды')),
                ('award_type', models.CharField(choices=[('diploma', 'Диплом'), ('gratitude', 'Благодарность')], default='diploma', max_length=20, verbose_name='Тип документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['-created_at'],
            },
        ),
    ]
