# Generated by Django 6.0.5 on 2026-05-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaward',
            name='award_type',
            field=models.CharField(choices=[('diploma', 'Диплом'), ('gratitude', 'Сертификаты')], default='diploma', max_length=20, verbose_name='Тип документа'),
        ),
    ]
