# Generated by Django 6.0.5 on 2026-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinicaward_award_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Описание фото (необязательно)')),
                ('image', models.ImageField(upload_to='clinic/gallery/', verbose_name='Фотография центра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фотография центра',
                'verbose_name_plural': 'Галерея: О клинике',
                'ordering': ['-created_at'],
            },
        ),
    ]
