# Generated by Django 6.0.5 on 2026-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinicgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пациента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий пациента')),
                ('target_type', models.CharField(max_length=100, verbose_name='Тип сущности (Врач/Методика)')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='ID сущности')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Обработано администратором')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на прием',
                'verbose_name_plural': 'Заявки на прием',
                'ordering': ['-created_at'],
            },
        ),
    ]
