# Generated by Django 6.0.5 on 2026-06-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_callbacklead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorgallery',
            options={'ordering': ['id'], 'verbose_name': 'Фотография галереи врача', 'verbose_name_plural': 'Галерея картинок врача'},
        ),
    ]
