# Generated by Django 6.0.5 on 2026-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_doctorgallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надзаголовок (подзаголовок)')),
                ('text', models.TextField(verbose_name='Описание / Текст слайда')),
                ('image', models.ImageField(upload_to='clinic/banners/', verbose_name='Фоновое изображение')),
                ('button_text', models.CharField(default='Подробнее', max_length=100, verbose_name='Текст кнопки')),
                ('link', models.CharField(default='/contacts', max_length=255, verbose_name='Ссылка для кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд баннера',
                'verbose_name_plural': 'Слайды баннера',
                'ordering': ['order'],
            },
        ),
    ]
