# Generated by Django 6.0.5 on 2026-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_bannerslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodgallery',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Фотография галереи', 'verbose_name_plural': 'Галерея картинок методики'},
        ),
        migrations.AddField(
            model_name='methodgallery',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Чем меньше число, тем раньше фото отобразится в слайдере', verbose_name='Порядок в слайдере'),
        ),
    ]
