# Generated by Django 6.0.5 on 2026-06-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_methodgallery_options_methodgallery_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О клинике', max_length=200)),
                ('description', models.TextField(help_text='Основной текст описания')),
                ('founder_name', models.CharField(default='Огулов Александр Тимофеевич', max_length=200)),
                ('founder_photo', models.ImageField(blank=True, null=True, upload_to='clinic/founders/')),
                ('founder_description', models.TextField(help_text='Описание достижений основателя')),
                ('video_url', models.URLField(help_text='Ссылка на YouTube видео')),
                ('video_preview', models.ImageField(blank=True, null=True, upload_to='clinic/video/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'О клинике (Главная)',
                'verbose_name_plural': 'О клинике (Главная)',
            },
        ),
        migrations.CreateModel(
            name='ClinicGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Для SEO оптимизации', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Сортировка')),
                ('about_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='clinic.clinicabout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
