# Generated by Django 6.0.5 on 2026-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/gallery/', verbose_name='Доп. foto'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0.0)), name='product_price_cannot_be_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('old_price__gte', 0.0), ('old_price__isnull', True), _connector='OR'), name='product_old_price_cannot_be_negative'),
        ),
    ]
