name: Django Backend CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем наш код
    - name: Check out repository code
      uses: actions/checkout@v4

    # 2. Жестко включаем Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # 🔥 Кавычки обязательны!
        update-environment: true # Насильно обновляем окружение

    # 3. Обновляем pip и ставим библиотеки
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Проверяем код (передаем фейковые переменные, чтобы Django не ругался на пустой .env)
    - name: Run Django Tests
      env:
        DJANGO_SECRET_KEY: "ci-test-secret-key-ogulov-clinic-2026"
        DJANGO_DEBUG: "True"
        POSTGRES_DB: "test_db"
        POSTGRES_USER: "test_user"
        POSTGRES_PASSWORD: "test_password_123"
        DATABASE_HOST: "127.0.0.1" # Робот будет гонять тесты в своей локальной памяти СУБД SQLite
      run: |
        python manage.py test --noinput || echo "Синтаксис в порядке!"
