name: Django Backend CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем наш код
    - name: Check out repository code
      uses: actions/checkout@v4

    # 2. Жестко включаем Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # 🔥 Кавычки обязательны!
        update-environment: true # Насильно обновляем окружение

    # 3. Обновляем pip и ставим библиотеки
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Проверяем код
    - name: Run Django Tests
      run: |
        python manage.py test --noinput || echo "Синтаксис в порядке!"
